### ISSUE TITLE
HTTP Status Crashes Hubot

### ISSUE THREAD

**Issue by kkirsche** [hubot-scripts/hubot-http-status#3]
When running `hubot http status 401` I get the following error:

``` shell
[Tue Oct 13 2015 10:22:57 GMT-0400 (EDT)] ERROR TypeError: Cannot read property 'parent' of null
  at exports.update (/Users/exampleuser/git/hubot/node_modules/hubot-http-status/node_modules/cheerio/lib/parse.js:64:25)
  at module.exports (/Users/exampleuser/git/hubot/node_modules/hubot-http-status/node_modules/cheerio/lib/parse.js:26:3)
  at Function.exports.load (/Users/exampleuser/git/hubot/node_modules/hubot-http-status/node_modules/cheerio/lib/static.js:19:14)
  at /Users/exampleuser/git/hubot/node_modules/hubot-http-status/src/http-status.coffee:25:11, <js>:12:21
  at ClientRequest.<anonymous> (/Users/exampleuser/git/hubot/node_modules/hubot/node_modules/scoped-http-client/src/index.js:99:20)
  at ClientRequest.emit (events.js:107:17)
  at TLSSocket.socketErrorListener (_http_client.js:271:9)
  at TLSSocket.emit (events.js:129:20)
  at net.js:459:14
  at process._tickCallback (node.js:355:11)
```

**Comment by delianides** [comment]
I need more information to troubleshoot. I've verified that nothing has changed on the Wikipedia page so I'm not sure why cheerio wouldn't be able to find the id on the page.

What adapter are you using? and what version of Cheerio?

**Comment by kkirsche** [comment]
Adapter: [nandub/hubot-irc](https://github.com/nandub/hubot-irc)
Cheerio: 0.16.0 is what is in `node_modules/hubot-http-status/node_modules/cheerio`

**Comment by davidkarlsen** [comment]
Same here. Slack adapter. using https_proxy / http_proxy
